name: CI

on: [push, pull_request]

jobs:

  build:
    
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install MacKernelSDK
      run: |
        git clone --depth=1 https://github.com/acidanthera/MacKernelSDK.git

    - name: Release Build
      run: |
        xcodebuild -scheme "IntelBluetoothFirmware" -configuration Release | xcpretty && exit ${PIPESTATUS[0]}

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/*/*.zip
